// Generated by CoffeeScript 1.3.3
(function() {
  var HOST, LISTENING_PORT, app, express, io, server;

  io = require('socket.io');

  express = require('express');

  LISTENING_PORT = 8010;

  HOST = "http://localhost";

  app = express();

  server = require('http').createServer(app);

  io = io.listen(server);

  server.listen(LISTENING_PORT);

  app.get('/', function(req, res) {
    console.log('hola');
    return res.sendfile(__dirname + '/client.html');
  });

  /*
  # Via express 2.x server
  app = express.createServer()
  io = io.listen app
  app.listen LISTENING_PORT
  */


  /*
  # Standalone
  io = io.listen LISTENING_PORT
  */


  io.sockets.on('connection', function(socket) {
    console.log('a user is connected to server');
    socket.send('connection received by the server');
    socket.on('message', function(message) {
      console.log(message);
      return socket.emit('news', {
        hello: 'world'
      });
    });
    socket.on('my other event', function(data) {
      return console.log(data);
    });
    socket.on('execute_console', function(func) {
      return func();
    });
    socket.on('sendName', function(name) {
      console.log("storing userName, " + name);
      return socket.set('userName', name, function() {
        return socket.emit('nameReceived');
      });
    });
    return socket.on('getName', function() {
      return socket.get('userName', function(err, ctxName) {
        console.log("emitting getname, " + ctxName);
        return socket.emit('getName', ctxName);
      });
    });
  });

}).call(this);
