// Generated by CoffeeScript 1.3.3
(function() {
  var HOST, LISTENING_PORT, app, express, io, server;

  io = require('socket.io');

  express = require('express');

  LISTENING_PORT = 8010;

  HOST = "http://localhost";

  app = express();

  server = require('http').createServer(app);

  io = io.listen(server);

  server.listen(LISTENING_PORT);

  app.get('/', function(req, res) {
    console.log('hola');
    return res.sendfile(__dirname + '/client.html');
  });

  /*
  # Via express 2.x server
  app = express.createServer()
  io = io.listen app
  app.listen LISTENING_PORT
  */


  /*
  # Standalone
  io = io.listen LISTENING_PORT
  */


  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    return socket.on('my other event', function(data) {
      return console.log(data);
    });
  });

}).call(this);
